version: '3.8'

services:
  oracle-db-poc:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db-poc
    ports:
      - "1521:1521"   # Porta padrão do Oracle Database
      - "5500:5500"   # Porta para Oracle Enterprise Manager
    environment:
      - ORACLE_PASSWORD=senha123
      - ORACLE_PDB=XEPDB1
      - ORACLE_SID=XE
    volumes:
      - oracle-data:/opt/oracle/oradata   # Persistência dos dados do banco
    restart: always
    networks:
      - poc-network

  zookeeper-poc:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-poc
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - poc-network

  kafka-poc:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-poc
    hostname: kafka-poc
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-poc:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-poc:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper-poc
    networks:
      - poc-network

  debezium-connect-poc:
    image: debezium/connect:3.0.0.Final
    container_name: debezium-connect-poc
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka-poc:9092
      GROUP_ID: "debezium-connect-group"
      CONFIG_STORAGE_TOPIC: "debezium-configs"
      OFFSET_STORAGE_TOPIC: "debezium-offsets"
      STATUS_STORAGE_TOPIC: "debezium-status"
      CONNECT_PLUGIN_PATH: "/kafka/connect,/usr/share/java"
    depends_on:
      - kafka-poc
    volumes:
      - ./ojdbc8.jar:/usr/share/java/ojdbc8.jar
      - ./debezium-connector-oracle-3.0.4.Final.jar:/usr/share/java/debezium-connector-oracle-3.0.4.Final.jar
      - ./debezium-connector-oracle:/usr/share/java/debezium-connector-oracle
    networks:
      - poc-network

  kafka-ui-poc:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-poc
    environment:
      KAFKA_CLUSTERS_0_NAME: "My Kafka Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-poc:9092"  # Use o nome do serviço Kafka dentro do Docker
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper-poc:2181"
    ports:
      - "8085:8080"  # Porta para acessar a UI
    depends_on:
      - kafka-poc
      - zookeeper-poc
    restart: always
    networks:
      - poc-network


volumes:
  oracle-data:
    driver: local
networks:
  poc-network:
    driver: bridge

